refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console
  file_appender:
    kind: rolling_file
    path: "log/application.log"
    append: true
    encoder:
      pattern: "{d(%+)(utc)} [{f}:{L}] {h({l})} {M}:{m}{n}"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 10 mb
      roller:
        kind: fixed_window
        pattern: log/application.{}.log
        count: 10
        base: 1

root:
  level: info
  appenders:
    - stdout
    - file_appender
